package converter

import (
	"strings"
	"testing"

	"github.com/DelineaXPM/delinea-netconfig/pkg/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCiscoACLConverter_Convert(t *testing.T) {
	tests := []struct {
		name    string
		entries []types.NetworkEntry
		want    []string // Lines that must be present in output
		wantNot []string // Lines that must NOT be present
		wantErr bool
	}{
		{
			name: "single outbound rule with single port",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "platform",
					Region:      "us",
					Type:        "ipv4",
					Values:      []string{"10.0.0.0/24"},
					Protocol:    "tcp",
					Ports:       []int{443},
					Description: "Platform API",
				},
			},
			want: []string{
				"! Delinea Platform Network Requirements",
				"! Generated by delinea-netconfig",
				"! Outbound Rules (Egress)",
				"ip access-list extended DELINEA-OUTBOUND",
				" 10 remark platform - Platform API",
				" 11 permit tcp any 10.0.0.0 0.0.0.255 eq 443",
			},
		},
		{
			name: "single inbound rule with port range",
			entries: []types.NetworkEntry{
				{
					Direction:   "inbound",
					Service:     "webhooks",
					Region:      "us",
					Type:        "ipv4",
					Values:      []string{"192.168.1.0/24"},
					Protocol:    "tcp",
					Ports:       []int{8080, 8081, 8082, 8083},
					Description: "Webhook callbacks",
				},
			},
			want: []string{
				"! Inbound Rules (Ingress)",
				"ip access-list extended DELINEA-INBOUND",
				" 10 remark webhooks - Webhook callbacks",
				" 11 permit tcp 192.168.1.0 0.0.0.255 any range 8080 8083",
			},
		},
		{
			name: "hostname entry becomes remark",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "platform",
					Region:      "us",
					Type:        "hostname",
					Values:      []string{"api.example.com"},
					Protocol:    "tcp",
					Ports:       []int{443},
					Description: "API endpoint",
				},
			},
			want: []string{
				"! Outbound Rules (Egress)",
				" remark platform - API endpoint (hostname: api.example.com)",
			},
			wantNot: []string{
				"permit tcp",
			},
		},
		{
			name: "multiple values create multiple rules",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "cdn",
					Region:      "global",
					Type:        "ipv4",
					Values:      []string{"1.2.3.0/24", "5.6.7.0/24"},
					Protocol:    "tcp",
					Ports:       []int{443},
					Description: "CDN endpoints",
				},
			},
			want: []string{
				" 10 remark cdn - CDN endpoints",
				" 11 permit tcp any 1.2.3.0 0.0.0.255 eq 443",
				" 20 remark cdn - CDN endpoints",
				" 21 permit tcp any 5.6.7.0 0.0.0.255 eq 443",
			},
		},
		{
			name: "UDP protocol",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "dns",
					Region:      "global",
					Type:        "ipv4",
					Values:      []string{"8.8.8.8/32"},
					Protocol:    "udp",
					Ports:       []int{53},
					Description: "DNS queries",
				},
			},
			want: []string{
				" 11 permit udp any host 8.8.8.8 eq 53",
			},
		},
		{
			name: "both protocol becomes ip",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "vpn",
					Region:      "global",
					Type:        "ipv4",
					Values:      []string{"10.0.0.1/32"},
					Protocol:    "both",
					Ports:       []int{},
					Description: "VPN gateway",
				},
			},
			want: []string{
				" 11 permit ip any host 10.0.0.1",
			},
		},
		{
			name: "CIDR to wildcard mask conversions",
			entries: []types.NetworkEntry{
				{
					Direction: "outbound",
					Service:   "test",
					Region:    "global",
					Type:      "ipv4",
					Values: []string{
						"10.0.0.0/8",
						"172.16.0.0/16",
						"192.168.0.0/19",
						"192.168.32.0/21",
						"192.168.40.0/22",
					},
					Protocol:    "tcp",
					Ports:       []int{443},
					Description: "Test CIDR conversions",
				},
			},
			want: []string{
				"permit tcp any 10.0.0.0 0.255.255.255 eq 443",
				"permit tcp any 172.16.0.0 0.0.255.255 eq 443",
				"permit tcp any 192.168.0.0 0.0.31.255 eq 443",
				"permit tcp any 192.168.32.0 0.0.7.255 eq 443",
				"permit tcp any 192.168.40.0 0.0.3.255 eq 443",
			},
		},
		{
			name: "host address without CIDR",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "server",
					Region:      "us",
					Type:        "ipv4",
					Values:      []string{"192.168.1.100"},
					Protocol:    "tcp",
					Ports:       []int{22},
					Description: "SSH server",
				},
			},
			want: []string{
				"permit tcp any host 192.168.1.100 eq 22",
			},
		},
		{
			name: "multiple non-consecutive ports use first port",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "app",
					Region:      "us",
					Type:        "ipv4",
					Values:      []string{"10.0.0.0/24"},
					Protocol:    "tcp",
					Ports:       []int{80, 443, 8080},
					Description: "Multiple ports",
				},
			},
			want: []string{
				"permit tcp any 10.0.0.0 0.0.0.255 eq 80",
			},
		},
		{
			name: "both outbound and inbound rules",
			entries: []types.NetworkEntry{
				{
					Direction:   "outbound",
					Service:     "api",
					Region:      "us",
					Type:        "ipv4",
					Values:      []string{"10.0.0.0/24"},
					Protocol:    "tcp",
					Ports:       []int{443},
					Description: "API calls",
				},
				{
					Direction:   "inbound",
					Service:     "webhooks",
					Region:      "us",
					Type:        "ipv4",
					Values:      []string{"192.168.0.0/24"},
					Protocol:    "tcp",
					Ports:       []int{8443},
					Description: "Webhook callbacks",
				},
			},
			want: []string{
				"! Outbound Rules (Egress)",
				"ip access-list extended DELINEA-OUTBOUND",
				"permit tcp any 10.0.0.0 0.0.0.255 eq 443",
				"! Inbound Rules (Ingress)",
				"ip access-list extended DELINEA-INBOUND",
				"permit tcp 192.168.0.0 0.0.0.255 any eq 8443",
			},
		},
		{
			name:    "empty entries",
			entries: []types.NetworkEntry{},
			want: []string{
				"! Delinea Platform Network Requirements",
				"! Generated by delinea-netconfig",
				"! End of ACL",
			},
			wantNot: []string{
				"ip access-list extended",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := &CiscoACLConverter{}
			got, err := c.Convert(tt.entries)

			if tt.wantErr {
				require.Error(t, err)
				return
			}

			require.NoError(t, err)
			output := string(got)

			// Check for required lines
			for _, want := range tt.want {
				assert.Contains(t, output, want, "output should contain: %s", want)
			}

			// Check for lines that should NOT be present
			for _, wantNot := range tt.wantNot {
				assert.NotContains(t, output, wantNot, "output should NOT contain: %s", wantNot)
			}
		})
	}
}

func TestCiscoACLConverter_cidrToWildcardMask(t *testing.T) {
	tests := []struct {
		name string
		cidr string
		want string
	}{
		{"slash 8", "8", "0.255.255.255"},
		{"slash 16", "16", "0.0.255.255"},
		{"slash 19", "19", "0.0.31.255"},
		{"slash 21", "21", "0.0.7.255"},
		{"slash 22", "22", "0.0.3.255"},
		{"slash 24", "24", "0.0.0.255"},
		{"slash 25", "25", "0.0.0.127"},
		{"slash 26", "26", "0.0.0.63"},
		{"slash 27", "27", "0.0.0.31"},
		{"slash 28", "28", "0.0.0.15"},
		{"slash 29", "29", "0.0.0.7"},
		{"slash 30", "30", "0.0.0.3"},
		{"slash 31", "31", "0.0.0.1"},
		{"slash 32", "32", "0.0.0.0"},
		{"unknown CIDR defaults to host", "99", "0.0.0.0"},
	}

	c := &CiscoACLConverter{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := c.cidrToWildcardMask(tt.cidr)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestCiscoACLConverter_formatAddress(t *testing.T) {
	tests := []struct {
		name string
		addr string
		want string
	}{
		{
			name: "any keyword",
			addr: "any",
			want: "any",
		},
		{
			name: "CIDR notation /24",
			addr: "192.168.1.0/24",
			want: "192.168.1.0 0.0.0.255",
		},
		{
			name: "CIDR notation /16",
			addr: "172.16.0.0/16",
			want: "172.16.0.0 0.0.255.255",
		},
		{
			name: "CIDR notation /32 (host)",
			addr: "10.0.0.1/32",
			want: "host 10.0.0.1",
		},
		{
			name: "IP without CIDR",
			addr: "192.168.1.100",
			want: "host 192.168.1.100",
		},
		{
			name: "already formatted with host keyword",
			addr: "host 10.0.0.1",
			want: "host 10.0.0.1",
		},
	}

	c := &CiscoACLConverter{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := c.formatAddress(tt.addr)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestCiscoACLConverter_formatPorts(t *testing.T) {
	tests := []struct {
		name  string
		ports []int
		want  string
	}{
		{
			name:  "empty ports",
			ports: []int{},
			want:  "",
		},
		{
			name:  "single port",
			ports: []int{443},
			want:  " eq 443",
		},
		{
			name:  "consecutive ports (range)",
			ports: []int{8080, 8081, 8082, 8083},
			want:  " range 8080 8083",
		},
		{
			name:  "non-consecutive ports (use first)",
			ports: []int{80, 443, 8080},
			want:  " eq 80",
		},
		{
			name:  "two consecutive ports (range)",
			ports: []int{8080, 8081},
			want:  " range 8080 8081",
		},
	}

	c := &CiscoACLConverter{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := c.formatPorts(tt.ports)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestCiscoACLConverter_areConsecutive(t *testing.T) {
	tests := []struct {
		name  string
		ports []int
		want  bool
	}{
		{
			name:  "empty",
			ports: []int{},
			want:  false,
		},
		{
			name:  "single port",
			ports: []int{443},
			want:  false,
		},
		{
			name:  "consecutive ports",
			ports: []int{8080, 8081, 8082, 8083},
			want:  true,
		},
		{
			name:  "non-consecutive ports",
			ports: []int{80, 443, 8080},
			want:  false,
		},
		{
			name:  "two consecutive ports",
			ports: []int{8080, 8081},
			want:  true,
		},
		{
			name:  "gap in middle",
			ports: []int{8080, 8081, 8083},
			want:  false,
		},
	}

	c := &CiscoACLConverter{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := c.areConsecutive(tt.ports)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestCiscoACLConverter_Name(t *testing.T) {
	c := &CiscoACLConverter{}
	assert.Equal(t, "Cisco ACL", c.Name())
}

func TestCiscoACLConverter_FileExtension(t *testing.T) {
	c := &CiscoACLConverter{}
	assert.Equal(t, "acl", c.FileExtension())
}

func TestCiscoACLConverter_formatACLRule(t *testing.T) {
	c := &CiscoACLConverter{}

	t.Run("full rule with description", func(t *testing.T) {
		rule := c.formatACLRule(10, "permit", "tcp", "any", "10.0.0.0/24", []int{443}, "Platform API", "platform")

		assert.Contains(t, rule, " 10 remark platform - Platform API")
		assert.Contains(t, rule, " 11 permit tcp any 10.0.0.0 0.0.0.255 eq 443")
	})

	t.Run("rule without ports", func(t *testing.T) {
		rule := c.formatACLRule(20, "permit", "ip", "any", "any", []int{}, "Allow all IP", "general")

		lines := strings.Split(strings.TrimSpace(rule), "\n")
		assert.Len(t, lines, 2) // remark + permit
		assert.Contains(t, lines[1], " 21 permit ip any any")
		assert.NotContains(t, lines[1], "eq")
	})

	t.Run("UDP protocol", func(t *testing.T) {
		rule := c.formatACLRule(30, "permit", "udp", "8.8.8.8/32", "any", []int{53}, "DNS", "dns")

		assert.Contains(t, rule, " 31 permit udp host 8.8.8.8 any eq 53")
	})
}
