package converter

import (
	"fmt"
	"strings"

	"github.com/DelineaXPM/delinea-platform/delinea-netconfig/pkg/types"
)

// CiscoACLConverter converts network entries to Cisco ACL format
type CiscoACLConverter struct{}

// Convert converts network entries to Cisco ACL format
func (c *CiscoACLConverter) Convert(entries []types.NetworkEntry) ([]byte, error) {
	var output strings.Builder

	// Write header comments
	output.WriteString("! Delinea Platform Network Requirements\n")
	output.WriteString("! Generated by delinea-netconfig\n")
	output.WriteString("!\n")

	// Group entries by direction
	outboundEntries := []types.NetworkEntry{}
	inboundEntries := []types.NetworkEntry{}

	for _, entry := range entries {
		if entry.Direction == "outbound" {
			outboundEntries = append(outboundEntries, entry)
		} else {
			inboundEntries = append(inboundEntries, entry)
		}
	}

	// Generate outbound ACL
	if len(outboundEntries) > 0 {
		output.WriteString("!\n! Outbound Rules (Egress)\n")
		output.WriteString("ip access-list extended DELINEA-OUTBOUND\n")

		aclNumber := 10
		for _, entry := range outboundEntries {
			// Skip hostname entries (ACL requires IP addresses)
			if strings.Contains(entry.Type, "hostname") {
				output.WriteString(fmt.Sprintf(" remark %s - %s (hostname: %s)\n",
					entry.Service, entry.Description, strings.Join(entry.Values, ", ")))
				continue
			}

			for _, value := range entry.Values {
				rule := c.formatACLRule(aclNumber, "permit", entry.Protocol, "any", value, entry.Ports, entry.Description, entry.Service)
				output.WriteString(rule)
				aclNumber += 10
			}
		}
	}

	// Generate inbound ACL
	if len(inboundEntries) > 0 {
		output.WriteString("!\n! Inbound Rules (Ingress)\n")
		output.WriteString("ip access-list extended DELINEA-INBOUND\n")

		aclNumber := 10
		for _, entry := range inboundEntries {
			// Skip hostname entries
			if strings.Contains(entry.Type, "hostname") {
				output.WriteString(fmt.Sprintf(" remark %s - %s (hostname: %s)\n",
					entry.Service, entry.Description, strings.Join(entry.Values, ", ")))
				continue
			}

			for _, value := range entry.Values {
				rule := c.formatACLRule(aclNumber, "permit", entry.Protocol, value, "any", entry.Ports, entry.Description, entry.Service)
				output.WriteString(rule)
				aclNumber += 10
			}
		}
	}

	// Add deny all at the end (implicit in Cisco, but explicit is better)
	output.WriteString("!\n! End of ACL\n")

	return []byte(output.String()), nil
}

// formatACLRule formats a single ACL rule
func (c *CiscoACLConverter) formatACLRule(seq int, action, protocol, source, dest string, ports []int, description, service string) string {
	var rule strings.Builder

	// Add remark for clarity
	if description != "" {
		rule.WriteString(fmt.Sprintf(" %d remark %s - %s\n", seq, service, description))
		seq++
	}

	// Format the ACL entry
	rule.WriteString(fmt.Sprintf(" %d %s", seq, action))

	// Protocol
	switch protocol {
	case "tcp":
		rule.WriteString(" tcp")
	case "udp":
		rule.WriteString(" udp")
	case "both":
		rule.WriteString(" ip") // Allow all IP protocols
	default:
		rule.WriteString(" ip")
	}

	// Source
	rule.WriteString(" " + c.formatAddress(source))

	// Destination
	rule.WriteString(" " + c.formatAddress(dest))

	// Ports (for TCP/UDP only)
	if (protocol == "tcp" || protocol == "udp") && len(ports) > 0 {
		rule.WriteString(c.formatPorts(ports))
	}

	rule.WriteString("\n")

	return rule.String()
}

// formatAddress converts CIDR notation to Cisco ACL format
func (c *CiscoACLConverter) formatAddress(addr string) string {
	if addr == "any" {
		return "any"
	}

	// Check if it's already formatted (starts with "host")
	if strings.HasPrefix(addr, "host ") {
		return addr
	}

	// Check if it's a CIDR notation
	if strings.Contains(addr, "/") {
		parts := strings.Split(addr, "/")
		if len(parts) == 2 {
			ip := parts[0]
			cidr := parts[1]

			// Special case: /32 should use "host" keyword
			if cidr == "32" {
				return fmt.Sprintf("host %s", ip)
			}

			// Convert CIDR to wildcard mask
			wildcardMask := c.cidrToWildcardMask(cidr)
			return fmt.Sprintf("%s %s", ip, wildcardMask)
		}
	}

	// If it's just an IP, treat it as /32 (host)
	return fmt.Sprintf("host %s", addr)
}

// cidrToWildcardMask converts CIDR prefix length to wildcard mask
func (c *CiscoACLConverter) cidrToWildcardMask(cidr string) string {
	wildcardMasks := map[string]string{
		"8":  "0.255.255.255",
		"16": "0.0.255.255",
		"19": "0.0.31.255",
		"21": "0.0.7.255",
		"22": "0.0.3.255",
		"24": "0.0.0.255",
		"25": "0.0.0.127",
		"26": "0.0.0.63",
		"27": "0.0.0.31",
		"28": "0.0.0.15",
		"29": "0.0.0.7",
		"30": "0.0.0.3",
		"31": "0.0.0.1",
		"32": "0.0.0.0",
	}

	if mask, ok := wildcardMasks[cidr]; ok {
		return mask
	}

	// Default to host if unknown
	return "0.0.0.0"
}

// formatPorts formats ports for ACL
func (c *CiscoACLConverter) formatPorts(ports []int) string {
	if len(ports) == 0 {
		return ""
	}

	if len(ports) == 1 {
		return fmt.Sprintf(" eq %d", ports[0])
	}

	// For multiple ports, use range if consecutive
	if c.areConsecutive(ports) {
		return fmt.Sprintf(" range %d %d", ports[0], ports[len(ports)-1])
	}

	// Otherwise, just use the first port with eq
	// (Cisco ACL limitations - would need separate rules for multiple non-consecutive ports)
	return fmt.Sprintf(" eq %d", ports[0])
}

// areConsecutive checks if ports are consecutive
func (c *CiscoACLConverter) areConsecutive(ports []int) bool {
	if len(ports) <= 1 {
		return false
	}

	for i := 1; i < len(ports); i++ {
		if ports[i] != ports[i-1]+1 {
			return false
		}
	}
	return true
}

// Name returns the name of the converter
func (c *CiscoACLConverter) Name() string {
	return "Cisco ACL"
}

// FileExtension returns the file extension for Cisco ACL files
func (c *CiscoACLConverter) FileExtension() string {
	return "acl"
}
