package converter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/DelineaXPM/delinea-platform/delinea-netconfig/pkg/types"
)

// TerraformConverter converts network entries to Terraform HCL format
type TerraformConverter struct{}

// Convert converts network entries to Terraform variables
func (c *TerraformConverter) Convert(entries []types.NetworkEntry) ([]byte, error) {
	buf := new(bytes.Buffer)

	// Write header
	fmt.Fprintln(buf, "# Delinea Platform Network Requirements")
	fmt.Fprintln(buf, "# Generated by delinea-netconfig")
	fmt.Fprintln(buf, "# https://github.com/DelineaXPM/delinea-platform")
	fmt.Fprintln(buf)

	// Group entries by direction, service, region, and type
	variableGroups := groupEntriesForTerraform(entries)

	// Get sorted variable names for consistent output
	varNames := make([]string, 0, len(variableGroups))
	for varName := range variableGroups {
		varNames = append(varNames, varName)
	}
	sort.Strings(varNames)

	// Generate variables in sorted order
	for _, varName := range varNames {
		c.writeVariable(buf, varName, variableGroups[varName])
	}

	return buf.Bytes(), nil
}

// Name returns the name of the converter
func (c *TerraformConverter) Name() string {
	return "Terraform"
}

// FileExtension returns the file extension for Terraform files
func (c *TerraformConverter) FileExtension() string {
	return "tf"
}

// terraformVarData holds the data for a Terraform variable
type terraformVarData struct {
	Description string
	Values      []string
	Redundancy  string
}

// groupEntriesForTerraform groups entries into Terraform variables
func groupEntriesForTerraform(entries []types.NetworkEntry) map[string]terraformVarData {
	groups := make(map[string]terraformVarData)

	for _, entry := range entries {
		// Only create variables for IP addresses (not hostnames)
		if entry.Type != "ipv4" && entry.Type != "ipv6" {
			continue
		}

		// Create variable name: delinea_{direction}_{service}_{region}_{type}
		varName := fmt.Sprintf("delinea_%s_%s_%s_%s",
			entry.Direction,
			sanitizeForTerraform(entry.Service),
			entry.Region,
			entry.Type,
		)

		// Add redundancy suffix if present
		if entry.Redundancy != "" {
			varName = fmt.Sprintf("%s_%s", varName, entry.Redundancy)
		}

		// Create or update variable data
		varData := groups[varName]
		if varData.Description == "" {
			varData.Description = fmt.Sprintf("%s - %s (%s)", entry.Service, entry.Description, entry.Region)
		}
		varData.Values = append(varData.Values, entry.Values...)
		varData.Redundancy = entry.Redundancy

		groups[varName] = varData
	}

	return groups
}

// writeVariable writes a Terraform variable to the buffer
func (c *TerraformConverter) writeVariable(buf *bytes.Buffer, name string, data terraformVarData) {
	// Sort values for consistent output
	values := make([]string, len(data.Values))
	copy(values, data.Values)
	sort.Strings(values)

	fmt.Fprintf(buf, "variable %q {\n", name)
	fmt.Fprintf(buf, "  description = %q\n", data.Description)
	fmt.Fprintln(buf, "  type        = list(string)")
	fmt.Fprintln(buf, "  default = [")
	for _, value := range values {
		fmt.Fprintf(buf, "    %q,\n", value)
	}
	fmt.Fprintln(buf, "  ]")
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

// sanitizeForTerraform sanitizes a string to be used in a Terraform variable name
func sanitizeForTerraform(s string) string {
	// Replace hyphens and other invalid characters with underscores
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, ".", "_")
	return strings.ToLower(s)
}
