# Delinea Platform Network Requirements
# Generated by delinea-netconfig
# https://github.com/DelineaXPM/delinea-platform

variable "delinea_inbound_webhooks_us_ipv4" {
  description = "webhooks - Webhook endpoints from <tenant> (us)"
  type        = list(string)
  default = [
    "13.68.202.64/29",
  ]
}

variable "delinea_outbound_static_service_global_ipv4" {
  description = "static_service - Static service without tenant placeholders (global)"
  type        = list(string)
  default = [
    "198.143.32.0/19",
    "199.83.128.0/21",
  ]
}

